[server]
headless = true
maxUploadSize = 10
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#E53935"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#1A1C23"
textColor = "#FAFAFA"
